
baseurl         = "https://blog.netsoc.co/"
theme           = "hugo-casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 10
#SectionPagesMenu = "main"
title       = "Blog | UCC Netsoc"
subtitle    = "The gears and cogs behind UCC Netsoc revealed. Updated from time to time with posts about how we develop and manage the society and it's services"
copyright   = "© 2020 UCC Networking Society. All rights reserved. Theme is Casper, Website Created by Michael Forde"

[params]

  cover       = "img/background.jpg"
  description = "UCC Netsoc Dev Blog"
  metaDescription = "UCC Netsoc Dev Blog"
  googleAnalytics = ""
  customCSS = ["css/main.css"]
  RSSLink = ""
  hjsStyle = "default"

  twitterName = "uccnetsoc"
  fbName = "NetsocUCC"
  githubName = "UCCNetworkingSociety"

  logo = "img/netsoc.png"
  orgName = "UCC Netsoc"
  orgWebsite = "https://www.netsoc.co/"
  orgDescription = "Here is a description placeholder for your org"

  author = "Netsoc"
  authorAvatar = "img/netsoc_black.jpg"
  authorLocation = "Cork, IE"
  authorWebsite = "https://www.netsoc.co/"
  authorDescription = "UCC Networking and Technology Society"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[blackfriday]
  hrefTargetBlank = true

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Tutorials"
  url = "/tags/tutorials/"
  weight = 100

[[menu.main]]
  name = "Dev Projects"
  url = "/tags/dev/"
  weight = 99

[[menu.main]]
  name = "Wiki"
  url = "http://wiki.netsoc.co"
  weight = 95

[[menu.main]]
  name = "Archive"
  url = "/tags/archive/"
  weight = 70
